import os
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

# =========================
# CONSTANTS
# =========================

DATA_PATH = os.path.join("Datasets", "processed", "ipl_dot_ball_dataset.csv")

PLOT_THEME = "plotly_dark"

# =========================
# LOAD DATA
# =========================

print("Loading dataset...")
df = pd.read_csv(DATA_PATH)
print(f"Loaded {len(df):,} rows")

# =========================
# TEAM ANALYSIS
# =========================

team_analysis = (
    df.groupby("batting_team")
    .agg(
        dot_balls=("is_dot_ball", "sum"),
        trees_generated=("trees_generated", "sum"),
        co2_offset_kg=("co2_offset_kg", "sum"),
    )
    .reset_index()
    .sort_values("trees_generated", ascending=False)
)

print("\n===== TOP TEAMS =====")
print(team_analysis.head(10))

# =========================
# BOWLER ANALYSIS
# =========================

bowler_analysis = (
    df.groupby("bowler")
    .agg(
        dot_balls=("is_dot_ball", "sum"),
        trees_generated=("trees_generated", "sum"),
        co2_offset_kg=("co2_offset_kg", "sum"),
        total_balls=("is_dot_ball", "count"),
    )
    .reset_index()
)

bowler_analysis["dot_ball_pct"] = (
    bowler_analysis["dot_balls"] / bowler_analysis["total_balls"] * 100
).round(2)

bowler_analysis["green_impact_score"] = (
    bowler_analysis["trees_generated"] * bowler_analysis["dot_ball_pct"]
).round(4)

bowler_analysis = bowler_analysis.sort_values(
    by="green_impact_score",
    ascending=False,
)

print("\n===== TOP BOWLERS =====")
print(bowler_analysis.head(20))

# =========================
# PHASE ANALYSIS
# =========================

phase_analysis = (
    df.groupby("phase")
    .agg(
        dot_balls=("is_dot_ball", "sum"),
        trees_generated=("trees_generated", "sum"),
    )
    .reset_index()
)

print("\n===== PHASE ANALYSIS =====")
print(phase_analysis)

# =========================
# SEASON TREND
# =========================

season_analysis = (
    df.groupby("season")
    .agg(
        dot_balls=("is_dot_ball", "sum"),
        trees_generated=("trees_generated", "sum"),
        co2_offset_kg=("co2_offset_kg", "sum"),
    )
    .reset_index()
    .sort_values("season")
)

print("\n===== SEASON TREND =====")
print(season_analysis)

# =========================
# PLOTLY VISUALIZATIONS
# =========================

# ── Fig 1: Trees by Team (sorted bar) ──────────────────────────────────────
fig1 = px.bar(
    team_analysis.head(15),
    x="batting_team",
    y="trees_generated",
    color="trees_generated",
    color_continuous_scale="Greens",
    title="🌳 Trees Generated by Batting Team (Top 15)",
    labels={"batting_team": "Team", "trees_generated": "Trees Generated"},
    template=PLOT_THEME,
    text_auto=".2f",
)
fig1.update_layout(
    title_font_size=20,
    xaxis_tickangle=-35,
    coloraxis_showscale=False,
    plot_bgcolor="rgba(0,0,0,0)",
)
fig1.show()

# ── Fig 2: Season Trend (line + area) ──────────────────────────────────────
fig2 = px.area(
    season_analysis,
    x="season",
    y="trees_generated",
    markers=True,
    title="📈 Season-wise Trees Generated (Trend)",
    labels={"season": "Season", "trees_generated": "Trees Generated"},
    color_discrete_sequence=["#4CAF50"],
    template=PLOT_THEME,
)
fig2.update_traces(line_width=3, marker_size=8)
fig2.update_layout(title_font_size=20)
fig2.show()

# ── Fig 3: Phase Pie ───────────────────────────────────────────────────────
fig3 = px.pie(
    phase_analysis,
    values="trees_generated",
    names="phase",
    title="🏏 Trees Contribution by Match Phase",
    color_discrete_sequence=px.colors.sequential.Greens_r,
    template=PLOT_THEME,
    hole=0.4,
)
fig3.update_traces(textinfo="percent+label", pull=[0.05, 0.05, 0.05])
fig3.update_layout(title_font_size=20)
fig3.show()

# ── Fig 4: Top 20 Bowlers (green impact score) ─────────────────────────────
fig4 = px.bar(
    bowler_analysis.head(20),
    x="green_impact_score",
    y="bowler",
    orientation="h",
    color="dot_ball_pct",
    color_continuous_scale="Tealgrn",
    title="🎯 Top 20 Bowlers — Green Impact Score",
    labels={
        "bowler": "Bowler",
        "green_impact_score": "Green Impact Score",
        "dot_ball_pct": "Dot Ball %",
    },
    template=PLOT_THEME,
)
fig4.update_layout(
    title_font_size=20,
    yaxis={"categoryorder": "total ascending"},
    height=600,
)
fig4.show()

# ── Fig 5: CO2 Offset by Season ────────────────────────────────────────────
fig5 = px.bar(
    season_analysis,
    x="season",
    y="co2_offset_kg",
    color="co2_offset_kg",
    color_continuous_scale="mint",
    title="🌿 CO₂ Offset (kg) by IPL Season",
    labels={"season": "Season", "co2_offset_kg": "CO₂ Offset (kg)"},
    template=PLOT_THEME,
    text_auto=".0f",
)
fig5.update_layout(
    title_font_size=20,
    coloraxis_showscale=False,
    xaxis_tickangle=-35,
)
fig5.show()

print("\n✅ All visualizations generated successfully!")